version: 2
general:
  branches:
    only:
     - circleci # list of branches to build
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/deployment-terraform/azure

    steps:      
      - checkout:
          path: ~/deployment-terraform/
      
      - run:
          name: Update apt cache
          command: apt update
    
      - run:
          name: Install prereq
          command: "yes | apt install apt-transport-https curl git unzip lsb-release software-properties-common coreutils || :;"

      - run:
          name: download terraform
          command: curl https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip --output terraform.zip && unzip terraform.zip
          
      - run:
          name: adjust configs
          command: echo $config_file | base64 --decode > ~/deployment-terraform/azure/group_vars/all.yml
          
      - run:
          name: Add Ansible apt repo
          command: apt-add-repository ppa:ansible/ansible
      
      - run:
          name: Add Azure CLI repo
          command: |
            AZ_REPO=$(lsb_release -cs);
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list;
     
      - run:      
          name: Get Azure CLI Apt key
          command: curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          
      - run:
          name: Update apt cache again
          command: apt update
      
      - run:
          name: Install Azure CLI
          command: apt install azure-cli
          
      - run:
          name: Install ansible
          command: "yes | apt install ansible || :;"
      
      - run:
          name: login to azure
          command: az login --service-principal --username $az_login --password $az_pass --tenant $az_tenant

      - run:
          name: deploy infra
          command: ansible-playbook site.yml -e 'terraform_location=~/deployment-terraform/azure/terraform' -e 'resource_group_name=$az_rgname'
