version: 2
general:
  branches:
    only:
     - circleci # list of branches to build
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    working_directory: ~/deployment-terraform/azure/azure

    steps:
      - checkout

      - run:
          name: download terraform
          command: curl https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip --output terraform.zip && unzip terraform.zip
          
      - run:
          name: adjust configs
          command: cp ~/deployment-terraform/azure/azure/group_vars/all.yml.example ~/deployment-terraform/azure/azure/group_vars/all.yml
      
      - run:
          name: login to azure
          command: az login -u $az_login -p $az_pass

      - run:
          name: deploy infra
          command: |
            ansible-playbook site.yml -e 'terraform_location=~/deployment-terraform/azure/azure/terraform'