version: 2
general:
  branches:
    only:
     - circleci # list of branches to build
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    working_directory: ~/deployment/

    steps:
      - checkout

      - run:
          name: download terraform
          command: curl https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip --output terraform.zip && unzip terraform.zip
          
      - run:
          name: adjust configs
          command: echo $config_file > ~/deployment/azure/group_vars/all.yml
      
      - run:
          name: Add Azure CLI  
          command: |
            AZ_REPO=$(lsb_release -cs);
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list;
     
      - run:      
          name: Get Azure CLI Apt key
          command: "curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -"
      
      - run:
          name: Install Azure CLI
          command: sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install azure-cli
      
      - run:
          name: login to azure
          command: az login -u $az_login -p $az_pass

      - run:
          name: deploy infra
          command: ansible-playbook site.yml -e 'terraform_location=~/deployment-terraform' 